import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import Card from "../components/Card";
import { signIn, getSession } from "next-auth/react";
import { useState } from "react";

export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: "/dashboard",
        permanent: false,
      },
    };
  }
  return {
    props: {
      session: await getSession(context),
    },
  };
}

async function handleEmail(email: string) {
  const res = await signIn("email", {
    email: email,
  });
  console.log(res);
}

const LandingPage: NextPage = () => {
  const [userInfo, setUserInfo] = useState({ email: "" });

  return (
    <>
      <Head>
        <title>T-CAD</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-full bg-primary">
        <div className="m-auto">
          <Card
            html={
              <div className="mt-3 mb-6 h-fit w-full">
                <div className="flex w-fit flex-col sm:ml-16 sm:mr-16 md:ml-32 md:mr-32">
                  <div className=" flex items-center justify-center">
                    <Image
                      className=""
                      src="/logo.svg"
                      alt="Logo"
                      width={96}
                      height={96}
                    />
                    <h1 className="text-3xl"></h1>
                  </div>
                  <form className="pl-4 pr-4">
                    <p className="text-md font-light">Email Address:</p>
                    <input
                      value={userInfo.email}
                      className="h-8 rounded-md border-transparent bg-textField p-2 md:w-64 lg:w-72"
                      title="Username"
                      type="text"
                      onChange={(e) =>
                        setUserInfo({ ...userInfo, email: e.target.value })
                      }
                    />
                    <div className="flex items-center justify-center">
                      <div
                        onClick={() => handleEmail(userInfo.email)}
                        className="mt-7 ml-2 cursor-pointer"
                      >
                        <Image
                          src="/mail.svg"
                          alt="Logo"
                          width={48}
                          height={48}
                        />
                      </div>
                      <div
                        className="mt-7 ml-2 cursor-pointer"
                        onClick={() => signIn("discord")}
                      >
                        <Image
                          src="/discord-v2.svg"
                          alt="Logo"
                          width={48}
                          height={48}
                        />
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            }
          />
        </div>
      </div>
    </>
  );
};

export default LandingPage;
