import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";
import Card from "../components/Card";
import { signIn, signOut, getSession, useSession } from "next-auth/react";
import { FormEventHandler, useState } from "react";

import { useRouter } from "next/router";

const Home: NextPage = () => {

  const [userInfo, setUserInfo] = useState({ email: "" });
  // Check if user has a session

  const { data: session, status } = useSession();
  const router = useRouter();

  // If user has a session, redirect to dashboard

  if (status === "authenticated") {
    router.push("/dashboard");
  } else {
    const handleEmail = async () => {
      const res = await signIn("email", {
        email: userInfo.email,
      });
      console.log(res);
    };

    return (
      <>
        <Head>
          <title>T-CAD</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex h-screen w-full bg-primary">
          <div className="m-auto">
            <Card
              html={
                <div className="mt-3 mb-6 h-fit w-full">
                  <div className="flex w-fit flex-col sm:ml-16 sm:mr-16 md:ml-32 md:mr-32">
                    <div className="mb-4 flex items-center justify-center">
                      <Image
                        className=""
                        src="/logo.svg"
                        alt="Logo"
                        width={72}
                        height={72}
                      />
                      <h1 className="text-3xl"></h1>
                    </div>
                    <form className="pl-4 pr-4">
                      <p className="text-md font-light">Email Address:</p>
                      <input
                        value={userInfo.email}
                        className="h-8 rounded-md border-transparent bg-textField md:w-64 lg:w-72"
                        title="Username"
                        type="text"
                        onChange={(e) =>
                          setUserInfo({ ...userInfo, email: e.target.value })
                        }
                      />
                      <div className="flex items-center justify-center">
                        <div
                          onClick={() => handleEmail()}
                          className="mt-7 ml-2 cursor-pointer"
                        >
                          <Image
                            src="/mail.svg"
                            alt="Logo"
                            width={32}
                            height={32}
                          />
                        </div>
                        <div
                          className="mt-7 ml-2 cursor-pointer"
                          onClick={() => signIn("discord")}
                        >
                          <Image
                            src="/discord-v2.svg"
                            alt="Logo"
                            width={32}
                            height={32}
                          />
                        </div>
                      </div>
                      <div className="flex items-center justify-center pt-2 text-xs">
                        <p>
                          or{" "}
                          <Link className="underline" href="/">
                            create an account
                          </Link>
                        </p>
                      </div>
                    </form>
                  </div>
                </div>
              }
            />
          </div>
        </div>
      </>
    );
  }
};

export default Home;
